### ISSUE TITLE
Disable export button when there are no deadlines to download

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#101]
Right now it will download file with the text "error"

**Comment by co-decode** [comment]
I would like to work on this issue.
It seems many of your other contributors are students at Calgary.
Please let me know if it is okay for me to help out.

**Comment by tim-macphail** [comment]
> I would like to work on this issue. It seems many of your other contributors are students at Calgary. Please let me know if it is okay for me to help out.

Hi Cody, this project is currently under development by the Lifeline team at [Tech Start UCalgary](https://techstartucalgary.com)! My name is Tim and I'm the Project Manager for the team, the rest of the members are the contributors thus far.

I am open to outside help, but due to the nature of the organization I think it best if I consult the club execs as well as my project members to see if they're OK with this. In the meantime, feel free to [join the club discord](https://discord.gg/Sxj5QrxRPk) and ping me if you want. Are you a U of C student yourself?

**Comment by co-decode** [comment]
That's alright Tim, I will leave this to your team.
I'm not a student, just someone looking for new and exciting projects.
Best of luck with your efforts!

**Comment by tim-macphail** [comment]
> That's alright Tim, I will leave this to your team.
> I'm not a student, just someone looking for new and exciting projects.
> Best of luck with your efforts!

Sounds good, thanks for your interest. When the semester/project lifecycle ends on April 28th with our final showcase, the Lifeline will likely become open source if you're still interested in contributing 🙂
