### ISSUE TITLE
Develop 'Edit Assessment' dialogue component

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#108]
## Develop the 'Edit Assessment' dialogue component
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1615%3A10052&t=ASQzED2AhJdSQjEW-0

Is a drawer pullout on desktop and a whole screen on mobile.

![image](https://user-images.githubusercontent.com/70448914/218127349-a751240e-b0d9-4943-a5c0-a2fde074f787.png)

**Comment by cloudyyoung** [comment]
This component is to be changed in the Prototype so let's close this one for now
