### ISSUE TITLE
Implement Frontend Data Persistence

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#110]
### Using either localstorage or cookies, probably localstorage is more appropriate in this case
If I upload 5 courses and spend 5 minutes manually adjusting all the deadlines, then accidentally hit refresh or close the window, all my progress is gone and I have to start from scratch again. By storing this data in localstorage it will persist and I won't lose all my work.

**Comment by tim-macphail** [comment]
Better fix now available

**Comment by tim-macphail** [comment]
https://reactrouter.com/en/main/hooks/use-before-unload

**Comment by cloudyyoung** [comment]
Oh finally find it! I was searching for "persistent" and never be able to find.
