### ISSUE TITLE
Research pdf2htmlEX

### ISSUE THREAD

**Issue by cloudyyoung** [techstartucalgary/lifeline#119]
This library draws my attention: https://github.com/pdf2htmlEX/pdf2htmlEX

The problem with extracting plain text from table is when a sub/superscript number is a part of the assesment name, it's parsed into `Assignment 11` where the second one is a subscript number and refers to a description below the table. Converting the pdf to form of html can be a good solution as it provides a sense of format rather than only plain text.

After converting as html, we can use libraries like *BeautifulSoup* to extract more accurately.

**Comment by cloudyyoung** [comment]
And if this works, our PDF previewer is gonna be the same as we see in the Syllabuddy, because by then we will just put html (of the pdf) and highlight texts as we were highlingting html elements.

**Comment by tim-macphail** [comment]
This looks like exactly what we need! @jaza-k 
(prev comment deleted to avoid potential future legal issues [extra cautious ik])

**Comment by cloudyyoung** [comment]
[cpsc331.txt](https://github.com/techstartucalgary/lifeline/files/10718008/cpsc331.txt)
Change the file extension to html and open i browser.
