### ISSUE TITLE
Changes in Landing page branding

### ISSUE THREAD

**Issue by cloudyyoung** [techstartucalgary/lifeline#124]
Landing page prototype Feb 12: https://www.figma.com/proto/73ExdLYkvpk86rSrUbuBOO/Prototype?page-id=92%3A144&node-id=185%3A1153&viewport=-1040%2C308%2C0.38&scaling=scale-down-width&starting-point-node-id=185%3A1153&show-proto-sidebar=1

**Comment by tim-macphail** [comment]
We can lump #122 into the same PR as this. Also, do you want to entirely scrap the old logo in favor of this cursive one? I was a fan of the calendar with the heartbeat but you can make the call

**Comment by cloudyyoung** [comment]
Yeah this prototype has the updated landing page content in #122, whoever wants to work on that PR can already come to the new prototype.

Ignore the icon change in this prototype for now. I'm quite vacillating on the icon changes, I'm pretty sure the icon needs to be changed as the interfaces and typefaces has changed this much over time, but really unsure what it should be changed into.
