### ISSUE TITLE
Minor issues: Top App Bar

### ISSUE THREAD

**Issue by cloudyyoung** [techstartucalgary/lifeline#147]
This is just a placeholder issue and I'm working on it. Self-explanatory title too.

**Comment by tim-macphail** [comment]
None of my comments from https://github.com/techstartucalgary/lifeline/pull/139 were resolved, next time please wait for Bradley to have a chance to resolve these before merging

**Comment by cloudyyoung** [comment]
> None of my comments from https://github.com/techstartucalgary/lifeline/pull/139 were resolved, next time please wait for Bradley to have a chance to resolve these before merging

Isn't this PR only having one comment by you and it's already resolved by Bradley?

**Comment by tim-macphail** [comment]
> 

Maybe because they were review comments you didnt see them, but I asked him to delete comments and wrap the icons in buttons, which didn't get done before merging. 
![Screenshot from 2023-02-20 10-41-51](https://user-images.githubusercontent.com/70448914/220172040-4c89d329-8843-4508-a42f-75efe89edb71.png)
In the future I can just use regular comments to avoid confusion

**Comment by cloudyyoung** [comment]
> > 
> 
> Maybe because they were review comments you didnt see them, but I asked him to delete comments and wrap the icons in buttons, which didn't get done before merging. ![Screenshot from 2023-02-20 10-41-51](https://user-images.githubusercontent.com/70448914/220172040-4c89d329-8843-4508-a42f-75efe89edb71.png) In the future I can just use regular comments to avoid confusion

I see. It shows that these comments are _pending_, they're still in your draft kind of, and nobody can see them before you actually send them out by pressing until you do this:
<img width="679" alt="Screenshot 2023-02-20 at 5 19 27 PM" src="https://user-images.githubusercontent.com/20573623/220216677-6b800468-d98d-4421-b3d5-cab1d9e4af0f.png">


So there are two types of of comments you can put in a PR, one is  _single comment_ and it is just one comment by itself in a comment group, and another is an actually _code review comments_  in a group at a time and PR must resolve them to be able to be merged, which is the ones in your image.
