### ISSUE TITLE
(Wont fix) Upload files not working on iOS LAN

### ISSUE THREAD

**Issue by cloudyyoung** [techstartucalgary/lifeline#194]
Uploading syllabus is not working on iOS systems (iPhone, iPad) regardless of browser core (webkit / Safari, chrome./ Edge). The backend **receives no http requests**.

https://user-images.githubusercontent.com/20573623/221670690-785fdecd-7769-448a-9ccf-dbd8964a9412.MP4

**Comment by tim-macphail** [comment]
Interesting, I don't have an ios devices so this will have to be up to somebody else

**Comment by tim-macphail** [comment]
@cloudyyoung Did you add your phone's IP to the allowed CORS origins in the backend?

**Comment by cloudyyoung** [comment]
> 

I think it's a CORS issue, it's uploading in production. But adding `http://192.168.1.68:3000/` doesn't help in local. :(

**Comment by tim-macphail** [comment]
You would have to also change https://github.com/techstartucalgary/lifeline/blob/0bddcb15953c5f646506240b3ce9e6066c218e17/client/src/index.tsx#L16 to your server private IP

**Comment by tim-macphail** [comment]
There are tools that allow you to view your phone's browser console, that would help debug. I was able to do it before

**Comment by cloudyyoung** [comment]
This is.... really weird, like I've changed many things, and it works on laptop with my private ip, but it just never works on my phone, it's the same setup. I'll try another day, and I'm not feeling this needs to be fixed soon, phone works for production after all, just not in dev.

**Comment by tim-macphail** [comment]
> This is.... really weird, like I've changed many things, and it works on laptop with my private ip, but it just never works on my phone, it's the same setup. I'll try another day, and I'm not feeling this needs to be fixed soon, phone works for production after all, just not in dev.

@cloudyyoung 
Set the host to 0.0.0.0 to broadcast to LAN

https://github.com/techstartucalgary/lifeline/blob/46f19403b67e800ef2d4b3db9ca1cc965465633b/server/src/app.py#L62-L63

Set origins to ["*"]

https://github.com/techstartucalgary/lifeline/blob/46f19403b67e800ef2d4b3db9ca1cc965465633b/server/src/app.py#L29

Set axios base URL to your laptop ip

https://github.com/techstartucalgary/lifeline/blob/46f19403b67e800ef2d4b3db9ca1cc965465633b/client/src/index.tsx#L18
