### ISSUE TITLE
Frontend Data Persistence on Client Side Routing

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#213]
#202 Solved the problem of losing data when reloading/leaving the page, but there is still an issue.

If you upload a course, then click back (uses client side routing) to go back to landing page, then click forward again. The data is gone.

**Comment by cloudyyoung** [comment]
Save data on data change rather than on page close should solve.

**Comment by tim-macphail** [comment]
Closed by #260
