### ISSUE TITLE
Fix Course Deletion

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#259]
Deleting courses no longer works
Introduced in #255 

https://user-images.githubusercontent.com/70448914/227328127-482aa4f2-4240-4ef3-95b2-0eb002973c79.mp4

**Comment by tim-macphail** [comment]
@cloudyyoung 
https://github.com/techstartucalgary/lifeline/blob/735cfee4ae4a7655083475813ac968087c8a5aca/client/src/pages/Review/Review.tsx#L144
what is the reason for having `courseKeyURLParam` as a dependency here? (Deleting it fixes the issue)

**Comment by cloudyyoung** [comment]
> @cloudyyoung
> 
> https://github.com/techstartucalgary/lifeline/blob/735cfee4ae4a7655083475813ac968087c8a5aca/client/src/pages/Review/Review.tsx#L144
> 
> 
> what is the reason for having `courseKeyURLParam` as a dependency here? (Deleting it fixes the issue)

Seems like `courseKeyURLParam` was already there before #255 (didn't touch that line). But generally ESLint would want to have all the dependencies listed out on `useEffect`. 

Since this `useEffect` is meant to trigger once for page render, simply wrap it in a `useEffectOnce`.

**Comment by cloudyyoung** [comment]
We should in general, optimize the "saving" technique a little bit. There could be a few reasons that user is risking to not have their data saved to localstorage properly, when the data is only saved when they leave the page:
1. Browser crashes
2. Browser force quits
3. Browser hibernates inactive tabs

**Comment by tim-macphail** [comment]
> We should in general, optimize the "saving" technique a little bit. There could be a few reasons that user is risking to not have their data saved to localstorage properly, when the data is only saved when they leave the page:
> 
> 1. Browser crashes
> 2. Browser force quits
> 3. Browser hibernates inactive tabs
> 
> Without impact the performance too much, we should try to save data whenever data is changed. For example, save data on course deletion, assessment editing, etc.

I'll add this to the fix
