### ISSUE TITLE
Implement Client-Side routing in production

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#64]
Whenever you refresh a page that is not at the base URL, you get a 404 from GitHub pages.
![image](https://user-images.githubusercontent.com/70448914/215350558-1e8014e3-c585-4020-b499-aa5b18821269.png)
This is probably something to do with GitHub pages and React-Router-Dom and webpack not working together as intended

**Comment by cloudyyoung** [comment]
Create a `<404 />` page, then append `<Route path="/*" element={<404 />} />` to `App.tsx`

**Comment by tim-macphail** [comment]
On production, the back button on a course routes to a 404

**Comment by cloudyyoung** [comment]
> On production, the back button on a course routes to a 404

This issue was introduced in #103, the return button was routing to `/review` instead of `/app`. Fixed in #118.

**Comment by cloudyyoung** [comment]
Found this: https://github.com/rafgraph/spa-github-pages

GitHub pages doesn't support BrowserRouter so we would either use this workaround, or use other hosting platform.

**Comment by tim-macphail** [comment]
closed by [b12a88a](https://github.com/techstartucalgary/lifeline/commit/b12a88a9e0f3558fea7f307b9828063970d1b9fb)
