### ISSUE TITLE
Frontend: develop navigation drawer

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#78]
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1445%3A7119&t=BDHVwwNteJ12deku-0

**Comment by cloudyyoung** [comment]
### Navigation Drawer - Desktop
<img width="345" alt="Screenshot 2023-02-01 at 12 22 11 AM" src="https://user-images.githubusercontent.com/20573623/215977536-949a69d3-310f-45e7-9fa4-fc3c19e542f1.png">

1. Navigation drawer occupies the full height of the screen.
2. The metadate for each navigation item is for indicating the number of assessment for a course.
3. Each item is selectable, and only one of the items is active at a time.
4. "Add course" and "Export" are regular buttons.
5. Items are clickables, and should use `Button` component.

### Navigation Drawer - Phone
<img width="345" alt="Screenshot 2023-02-01 at 12 26 23 AM" src="https://user-images.githubusercontent.com/20573623/215978282-052cda04-c4f4-491f-8e82-b2ebfed88d7d.png">

6. In small screens, navigation drawer turns into a screen.
7. None of the items are selectables. They are regular buttons and will navigate to other page.


Developer might want to split them into two different components and develop both individually.
