### ISSUE TITLE
Frontend: develop app top bar (review page)

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#79]
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1445%3A7119&t=BDHVwwNteJ12deku-0

**Comment by cloudyyoung** [comment]
### App Top Bar

<img width="947" alt="Screenshot 2023-01-31 at 11 59 57 PM" src="https://user-images.githubusercontent.com/20573623/215973801-2685a0ef-d1d1-4346-875d-f7777f950d5d.png">

1. This component is full width wide.
2. It is divided into two sections, course key and topic on the left (left aligned), and action buttons on the right (right aligned).
3. When on scroll, the app top bar will dim. See: https://m3.material.io/components/top-app-bar/guidelines#4eab4f50-4a3e-4189-bce2-a46514cde1da
