### ISSUE TITLE
Frontend: develop course assessment card

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#80]
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1623%3A12580&t=0J1IrJNXT9ZxGcXW-0

**Comment by cloudyyoung** [comment]
### Course Assessment Card

1. Assessment cards should be clickable, and should use `Button` component as base.
2. The icon choice for an assessment will be determined at a later point, use a placeholder icon for this pr
