### ISSUE TITLE
Frontend: develop pdf viewer

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#81]
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1445%3A7119&t=BDHVwwNteJ12deku-0

Ideally we are able to annotate on this pdf. i.e. highlight the text where the deadline came from when hovering/tapping on the deadline. 

Ability to scroll + zoom / pinch + zoom is a plus

**Comment by cloudyyoung** [comment]
### PDF Viewer

This component has no complexity. It has a light outline and border radius.
