### ISSUE TITLE
Frontend: develop course info bento

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#82]
https://www.figma.com/file/73ExdLYkvpk86rSrUbuBOO/Prototype?node-id=1445%3A7119&t=BDHVwwNteJ12deku-0

![Image](https://user-images.githubusercontent.com/70448914/215959329-51ba64d0-d1d4-4574-8a5d-8c6faf986e20.png)

**Comment by cloudyyoung** [comment]
### Couse Information Bento

Some cards are clickable, use `Button` component as base for clickables. Description section should be expandable.

**Comment by tim-macphail** [comment]
> section

Which cards are clickable?

**Comment by cloudyyoung** [comment]
> > section
> 
> Which cards are clickable?

The description card is clickable to expand when the content is over 3 lines.
